name: Deploy safe apps
# Run on pushes to dev/main or PR
on:
  # Pull request hook without any config. Launches for every pull request
  pull_request:
  # Launches for pushes to main or dev
  push:
    branches:
      - main
      - development
  # Launches build when release is published
  release:
    types: [published]
env:
  REPO_NAME_ALPHANUMERIC: safereactapps

jobs:
  prepare-env:
    name: Prepare environment in the CI runner
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Env dependencies setup
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip python3-dev
          pip install awscli --upgrade --user

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Project dependencies setup, node version ${{ matrix.node-version }}
        run: yarn install --frozen-lockfile

  pr:
    name: Pull Request
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    needs: prepare-env
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - name: Test, Build, Deploy PR
        run: |
          npx nx affected --target=test --parallel --max-parallel=2
          npx nx affected --target=build --parallel --max-parallel=3
          npx nx affected --target=deploy:pr --parallel --max-parallel=2
        env:
          PR_NUMBER: ${{ github.event.number }}
          REVIEW_BUCKET_NAME: ${{ secrets.AWS_REVIEW_BUCKET_NAME }}
          REACT_APP_RPC_TOKEN: ${{ secrets.REACT_APP_RPC_TOKEN }}

      - name: 'PRaul: Comment PR with app URLs'
        if: success() && github.event.number
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            * [Compound app](${{ env.REVIEW_FEATURE_URL }}/compound/)
            * [WalletConnect app](${{ env.REVIEW_FEATURE_URL }}/wallet-connect/)
            * [Tx Builder App](${{ env.REVIEW_FEATURE_URL }}/tx-builder/)
            * [Drain Account App](${{ env.REVIEW_FEATURE_URL }}/drain-safe/)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
        env:
          REVIEW_FEATURE_URL: https://pr${{ github.event.number }}--${{ env.REPO_NAME_ALPHANUMERIC }}.review.gnosisdev.com

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: prepare-env

    steps:
      - uses: actions/checkout@v2

      - name: Test and Build
        run: |
          npx nx affected --target=test --parallel --max-parallel=2
          npx nx affected --target=build --parallel --max-parallel=3

      # Script to deploy to the dev environment
      - name: 'Deploy to S3: Develop'
        if: github.ref == 'refs/heads/development'
        run: npx nx affected --target=deploy:s3 --parallel --max-parallel=2
        env:
          BUCKET_NAME: ${{ secrets.AWS_DEV_BUCKET_NAME }}

      # Script to deploy to staging environment
      - name: 'Deploy to S3: Staging'
        if: github.ref == 'refs/heads/main'
        run: npx nx affected --base=last-release --target=deploy:s3 --parallel --max-parallel=2
        env:
          BUCKET_NAME: ${{ secrets.STAGING_BUCKET_NAME }}/current

      # Script to upload release files
      - name: 'Upload to S3: apps build files for production'
        if: startsWith(github.ref, 'refs/tags/v')
        run: npx nx affected --base=last-release --target=deploy:s3 --parallel --max-parallel=2
        env:
          BUCKET_NAME: ${{ secrets.STAGING_BUCKET_NAME }}/releases/${{ github.event.release.tag_name }}

      # Script to notify production deployments
      - run: bash ./scripts/prepare_production_deployment.sh
        if: success() && startsWith(github.ref, 'refs/tags/v')
        env:
          PROD_DEPLOYMENT_HOOK_TOKEN: ${{ secrets.PROD_DEPLOYMENT_HOOK_TOKEN }}
          PROD_DEPLOYMENT_HOOK_URL: ${{ secrets.PROD_DEPLOYMENT_HOOK_URL }}
          VERSION_TAG: ${{ github.event.release.tag_name }}
